### ISSUE TITLE
image exits without notice or log on bulk write

### ISSUE THREAD

**Issue by cdaringe** [klaemo/docker-couchdb#104]
# problem statement

- a naughty bulk write of 1M documents to the couchdb container forces it to exit. kind of DoS'ish
  - this does _not_ affect the raw couchdb binary. the normal couchdb binary kills the connection happily

# reproduce

- see https://github.com/cdaringe/docker-crash-couch for a short, sweet, easy reproducible thing™

![pound-couchdb mov](https://cloud.githubusercontent.com/assets/1003261/22621061/6f1483c4-eacf-11e6-9ec5-e3577bbd76e6.gif)

**Comment by garrensmith** [comment]
Kamino closed and cloned this issue to apache/couchdb-docker

**Comment by garrensmith** [comment]
Moved to https://github.com/apache/couchdb-docker/issues/5
