### ISSUE TITLE
Database perUser = true not working

### ISSUE THREAD

**Issue by patrickhaug** [klaemo/docker-couchdb#105]
In the image with the latest tag:

When setting the correct config to true, new dbs arent created after inserting new users.

**Comment by garrensmith** [comment]
Are you using couchdb 2.0 or 1.6?

**Comment by patrickhaug** [comment]
2.0

**Comment by garrensmith** [comment]
That plugin doesn't work for CouchDB 2.0 yet

All misspelling thanks to my iPhone.




On Sun, Feb 5, 2017 at 9:42 AM +0200, "Patrick Haug" <notifications@github.com> wrote:












2.0

**Comment by patrickhaug** [comment]
I thought it's built into couch 2. So whats this config for? Thanks for the answer.

**Comment by garrensmith** [comment]
There is a bug in it. 

All misspelling thanks to my iPhone.




On Sun, Feb 5, 2017 at 3:20 PM +0200, "Patrick Haug" <notifications@github.com> wrote:












I thought it's built into couch 2. So whats this config for? Thanks for the answer.

**Comment by garrensmith** [comment]
Closing since this isn't a docker issue
