### ISSUE TITLE
Build docker image on push to master

### ISSUE THREAD

**Issue by garrensmith** [klaemo/docker-couchdb#106]
HOw does the couchdb 2.0-dev tag get updated? Ideally it would be great if it was rebuilt on every push to couchdb master. That way we can stay nice and current.

**Comment by klaemo** [comment]
that would require a proper `Dockerfile` in the couchdb repo. Ages go I tried to implement that (https://github.com/apache/couchdb/pull/340), but it went nowhere.

Currently `2.0-dev` points to `2.0-rc1` which is rather odd (https://github.com/klaemo/docker-couchdb/blob/master/2.0-dev/Dockerfile#L59). It could point to commit hashes as well. On every push to this repo, docker hub rebuilds the images.

**Comment by garrensmith** [comment]
Kamino closed and cloned this issue to apache/couchdb-docker

**Comment by garrensmith** [comment]
Moved to https://github.com/apache/couchdb-docker/issues/4
