### ISSUE TITLE
Docker for Windows image

### ISSUE THREAD

**Issue by drnybble** [klaemo/docker-couchdb#107]
Other official repositories such as mongo and redis are now offering native Windows container images.

What are the plans for offering a CouchDB Windows image?

I have tried to build one myself. When I make the data directory a VOLUME Erlang quits shortly after the container starts. So there appears to be some kind of compatibility problem with CouchDB and Windows containers.

Let me know what information I could collect to diagnose why it doesn't work with native Windows docker.

**Comment by drnybble** [comment]
Will log for the official couchdb sorry about that

**Comment by drnybble** [comment]
FYI I have logged https://github.com/docker/docker/issues/31524

**Comment by apihlaja** [comment]
As far as I know, the core issue of [Alpine build](https://github.com/klaemo/docker-couchdb/issues/101#issuecomment-278703222) applies to Windows too (ie. unmaintained mozjs).

Does your mounts work generally? Ie. is this issue narrowed down to CouchDB and/or Erlang? Docker For Windows FAQ suggest it's not as straightforward as it's with Linux host:

[Q: Can I share local drives and filesystem with my Docker Machine VMs?
A: No, ....](https://docs.docker.com/docker-for-windows/faqs/#can-i-share-local-drives-and-filesystem-with-my-docker-machine-vms)

**Comment by drnybble** [comment]
As discussed in https://github.com/docker/docker/issues/31524 the cause of failure with Couch 1.6 is a defect in the Erlang version it uses. I have created a Dockerfile for Couch 2.0.0.1 and it works (the problem area of the Erlang code is extensively reworked and no longer has this problem). I am attaching the Dockerfile here if it is useful.

[Dockerfile.zip](https://github.com/klaemo/docker-couchdb/files/831903/Dockerfile.zip)

**Comment by klaemo** [comment]
@drnybble thanks for your interest in this :)

could you please copy&paste your Dockerfile inline here. People might not feel comfortable downloading zip files from random places on the internet ;-)

**Comment by drnybble** [comment]
Here it is...relies on you having downloaded the .msi already.
It seems that couchdb 2.0 requires a post-install step to configure the system for single node or clustering. I am still thinking of the best way to do that to avoids lots of errors in the logs about missing databases.

FROM microsoft/windowsservercore

# Switch the default shell used with RUN to PowerShell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

# REMARK: Temporary workaround for https://github.com/docker/docker/issues/31093
RUN set-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorityTimeLimit -Value 0 -Type DWord

COPY apache-couchdb-2.0.0.1.msi C:/

# Stop & remove the service that the .msi installs (there are no properties exposed by the .msi to prevent it in the first place)
# We need empty data and log directories to be able make those volumes under Windows but they have contents due to the service having run.
# I was unable to remove the .delete directory in the data directory, so renaming the directories was the easiest solution
# Also bind couchdb to other than localhost
RUN Start-Process 'C:\Windows\System32\msiexec.exe' -ArgumentList '/i C:\apache-couchdb-2.0.0.1.msi /qn' -wait ; \
    Remove-Item 'C:\apache-couchdb-2.0.0.1.msi' ; \
	C:\couchdb\bin\nssm.exe stop 'Apache CouchDB' > $null ; \
	C:\couchdb\bin\nssm.exe remove 'Apache CouchDB' confirm > $null ; \
	mv C:\couchdb\data C:\couchdb\_data ; \
	mv C:\couchdb\var\log C:\couchdb\var\_log ; \
	New-Item -Path C:\couchdb\data -Type directory > $null ; \
	New-Item -Path C:\couchdb\var\log -Type directory > $null ; \
    Copy-Item C:/CouchDB/etc/local.ini C:/CouchDB/etc/local.ini.orig ; \
    cat C:/CouchDB/etc/local.ini.orig | % { $_ -replace ';bind_address = 127.0.0.1', 'bind_address = 0.0.0.0' } | Out-File C:/CouchDB/etc/local.ini -encoding ASCII
	

WORKDIR C:/CouchDB/

VOLUME C:/couchdb/data
VOLUME C:/couchdb/var/log

EXPOSE 5984

CMD ./bin/couchdb.cmd

**Comment by antonyRoberts** [comment]
@drnybble When I try running this Docker it fails with
``` 
Sending build context to Docker daemon 3.584 kB
Step 1/10 : FROM microsoft/windowsservercore
latest: Pulling from microsoft/windowsservercore
3889bb8d808b: Pulling fs layer
503d87f3196a: Downloading
unknown blob
```
Have tried with Dockers's quick start terminal and using Windows PowerShell

**Comment by drnybble** [comment]
Are you running Docker for **Windows** on a fully patched system?

**Comment by antonyRoberts** [comment]
It's Docker Toolbox for Windows https://www.docker.com/products/docker-toolbox

**Comment by drnybble** [comment]
Docker Toolbox for Windows creates a Linux VM in VirtualBox. 
You need to install this:
https://www.docker.com/microsoft

Windows containers only work on Server 2016 or Windows 10

**Comment by garrensmith** [comment]
Kamino closed and cloned this issue to apache/couchdb-docker

**Comment by garrensmith** [comment]
I've moved this to here https://github.com/apache/couchdb-docker/issues/3
