### ISSUE TITLE
The $PATH is not set correct in your docker image

### ISSUE THREAD

**Issue by chankongching** [klaemo/docker-couchdb#109]
In order to make the docker image klaemo/couchdb to run, i have exported "PATH=/opt/couchdb/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/bin", 
/opt/couchdb/bin shldnt exists in $PATH when building by Dockerfile

**Comment by chankongching** [comment]
i just docker pull klaemo/couchdb:latest

**Comment by garrensmith** [comment]
I'm guessing this is fixed. If it isn't could you open a ticket here https://github.com/apache/couchdb-docker
