### ISSUE TITLE
Is Containerizing a DB a good choice?

### ISSUE THREAD

**Issue by bshikhar13** [klaemo/docker-couchdb#111]
Is it wise running a DB inside a container?

**Comment by klaemo** [comment]
In production probably not. For development it can be quite handy though.

**Comment by MikeMichel** [comment]
Why not? We are running couchdb in a container in production. everything is fine.

**Comment by bshikhar13** [comment]
I have been researching over the pros and cons of containerizing a Database and came across this article.

> people designed container solutions to deal with stateless applications that have ephemeral data. Containers spin up a quick microservice and then destroy it. This includes all the components of that container (including its cache and data). The transient nature of containers is because all of the components and services of that container are considered to be part of the container (essentially it’s all or nothing). Serving the container a data volume owned by the underlying OS by punching a hole through the container can be very challenging.

[Is Docker good for your Database](https://www.percona.com/blog/2016/11/16/is-docker-for-your-database/) by Jon Tobin

**Comment by MikeMichel** [comment]
Storage and infrastructure is key here. If you find a solution which handles moving containers (failing hosts) and deliverers performance as needed there speaks nothing against to use a db in a container. in fact we (customers) run hundreds of them. you can try it yourself at https://sloppy.io (14 days free trial):

![image](https://cloud.githubusercontent.com/assets/8025931/24896835/f2e500d4-1e96-11e7-8503-835d18810c93.png)

**Comment by garrensmith** [comment]
Closing this is not related to the docker image.
