### ISSUE TITLE
apt-transport-https removed after building but nodesource.list left

### ISSUE THREAD

**Issue by dnwe** [klaemo/docker-couchdb#115]
Out of the box you can't `apt-get update` in a Docker image that is `FROM klaemo/couchdb:2.0.0` unless you either (re-)install apt-transport-https or rm -f /etc/apt/sources.list.d/nodesource.list

The parent build should probably do the latter if it is going to remove the apt-transport-https pkg.

**Comment by klaemo** [comment]
This repo is no longer being maintained, please head over to https://github.com/apache/couchdb-docker
