### ISSUE TITLE
What erlang version should we use?

### ISSUE THREAD

**Issue by klaemo** [klaemo/docker-couchdb#12]
So, after reading [this](https://github.com/jhs/build-couchdb/commit/849fa7ec89d6f27f7758d13e57619bf1d41819e0) it seems as if wheezy's erlang 15.b1 is bad™. They recommend R16B03-1. wheezy-backports has 17.1. CouchDB 1.6 added support for erlang  17.
So, is 17.1 "too new"? Not tested well enough? Should we instead use erlang R16B03-1 from erlang-solutions.com?
Maybe @janl can shed some light on this situation?

**Comment by klaemo** [comment]
@joeybaker do have any input on this? I'd really like to get this resolved.

**Comment by joeybaker** [comment]
@chewbranca knows better than me, but I've also heard that R16B03-1 is the best bet.

**Comment by klaemo** [comment]
okay, and how do I get that version installed?

**Comment by joeybaker** [comment]
You'll have to compile from source. It's been a while since I tried, but this looks familiar via stackoverflow.

```
apt-get update
apt-get --fix-missing -y install build-essential m4 libncurses5-dev libssh-dev unixodbc-dev libgmp3-dev libwxgtk2.8-dev libglu1-mesa-dev fop xsltproc default-jdk
mkdir -p /src/erlang
cd /src/erlang
wget http://www.erlang.org/download/otp_src_R15B01.tar.gz 
tar -xvzf otp_src_R16B01.tar.gz 
chmod -R 777 otp_src_R16B01 
cd otp_src_R16B01 
./configure
make
make install
```
http://askubuntu.com/questions/190612/how-to-install-erlang-in-ubuntu-12-04

**Comment by klaemo** [comment]
If anyone wants to comment on the PR...I'm giving up ;-)

**Comment by janl** [comment]
which PR?

**Comment by klaemo** [comment]
@janl #17
