### ISSUE TITLE
couchdb 2.0-dev is failing

### ISSUE THREAD

**Issue by ngbinh** [klaemo/docker-couchdb#16]
This is what I get:

```
sudo docker run -p 15984:15984 -p 25984:25984 -p 35984:35984 --name couchdb-2.0 klaemo/couchdb:2.0-dev
Cluster is up, go to http://127.0.0.1:15984/_utils
Object Not Found
```

And after that: 
```
~  ᐅ netstat -na | grep 15984
~  ᐅ 
```

**Comment by klaemo** [comment]
Is this still a problem?

**Comment by ngbinh** [comment]
Sorry, will retry today and report back

**Comment by elecnix** [comment]
Reproduced original issue. Adding -d does the same, according to `docker logs`, but `docker run -i -t ...` works.

**Comment by ngbinh** [comment]
work for me now.

Thanks

**Comment by klaemo** [comment]
I documented the usage of `-i -t`...so...maybe we'll get away with that. ;-)
2.0-dev doesn't build at the moment anyway :D

**Comment by criloz** [comment]
it is a issue with the python file `/usr/src/couchdb/dev/run`, the issue will be present in some machines in other not. 

I add a additional line here

https://gist.github.com/criloz/48061014a7fb608c95ce#file-gistfile1-py-L231

it will wait for an additional second before continue with the other steps, it works for me.

**Comment by klaemo** [comment]
I applied your workaround, @criloz. Thank you for helping out :)

**Comment by carpogoryanin** [comment]
Have the same problem:
```
Object Not Found
```

And `-i -t` doesn't help for me

**Comment by thanos** [comment]
still a problem for me . using an EC2 image with Docker version 1.5.0, build a8a31ef/1.5.0
NAME="Amazon Linux AMI"
VERSION="2015.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2015.03"
PRETTY_NAME="Amazon Linux AMI 2015.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2015.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2015.03

**Comment by Gouthamve** [comment]
Hi, I am trying to get in running on my mac using Kitematic. And I am getting the ```Object not Found``` Error too even with -i -t.
