### ISSUE TITLE
 exec: "/entrypoint.sh": permission denied

### ISSUE THREAD

**Issue by criloz** [klaemo/docker-couchdb#19]
I was trying to run the docker image and got this error

exec: "/entrypoint.sh": permission denied

**Comment by klaemo** [comment]
Hi,
which version of the image were you using? 1.6 or 2.0-dev?
What's you OS, docker version etc. How exactly did you run the container?

**Comment by criloz** [comment]
image 1.6
OS: ubuntu 14.04 64 - bits
docker version: Docker version 1.0.1
I ran: docker run -p 5984:5984 -v ~/couchdb:/usr/local/var/lib/couchdb couchdb/admin

**Comment by klaemo** [comment]
There seem to be some problems with the stock docker version in ubuntu 14.04 and apparmor. Can you update to the latest docker as described [here](https://docs.docker.com/installation/ubuntulinux/#docker-maintained-package-installation) and try again?

**Comment by criloz** [comment]
done and not progress.  I will try again tomorrow, thank for the quick response, I will update here  any progress.

**Comment by criloz** [comment]
it is a issue with "/entrypoint.sh", I built a image without that ENTRYPOINT and the container ran normally

**Comment by klaemo** [comment]
we've had this issue before (see #4). it's not really a problem with `entrypoint.sh`, because it works for most people. I don't really know...

**Comment by brockoffdev** [comment]
Can confirm, also seeing this problem on 14.04 with apparmor...

**Comment by t0k4rt** [comment]
Got the same problem on a different  dockerfile, the problem maybe comes from a missing chmod +x on the entrypoint.sh file. Maybe you should try to add "RUN a chmod +x /entrypoint.sh" in the dockerfile after the COPY instruction.
That solved the problem in my case.

**Comment by klaemo** [comment]
I added the `chmod +x` bit, maybe it helps.

**Comment by alberto-grande** [comment]
The 
 "RUN chmod +x /entrypoint.sh"
worked for me.

**Comment by klaemo** [comment]
Okay, thanks for your feedback. I'll close this issue for now. If it in fact isn't resolved, feel free to re-open it.

**Comment by TemoPacheco** [comment]
$ chmod +x ./entrypoint.sh

And run the build process again

**Comment by klaemo** [comment]
It already is executable
<img width="563" alt="bildschirmfoto 2015-09-14 um 12 40 18" src="https://cloud.githubusercontent.com/assets/778624/9848029/d28d90a4-5add-11e5-8b5c-78be7737d78f.png">

Anyways...I think this is fixed

**Comment by daamdaam** [comment]
Adding 
"RUN chmod +x /entrypoint.sh"
 to my dockerfile worked for me.. thanks @t0k4rt, @alberto-grande :o)

**Comment by nikhil-dhiman** [comment]
Thanks for the solution.. chmod works for me

**Comment by gtog** [comment]
The chmod fix worked for me as well. Thanks for the great discussion.

**Comment by hopewise** [comment]
I had a similar problem with another image, 

    $chmod +x ./entrypoint.sh

worked for me :+1: 

No error with "RUN chmod +x /entrypoint.sh" but entrypoint.sh was not executed.. :-1:

**Comment by billysutomo** [comment]
have you use this command inside the dockerfile?
`ENTRYPOINT ["entrypoint.sh"]`

with that command the image will auto execute the entrypoint when you run the image.

**Comment by klaemo** [comment]
What is going on in this issue? Is there still a problem with the current, official image?

**Comment by mnewmedia** [comment]
Yes loaded yesterday, tried out today and got `"/docker-entrypoint.sh": permission denied`. Insert after the line `COPY ./docker-entrypoint.sh /` this line `RUN chmod +x /docker-entrypoint.sh` and it will work.

But after fixing this i'm having another issue `chmod: cannot access '/usr/local/etc/couchdb/*.ini': No such file or directory`.

**Comment by klaemo** [comment]
will hopefully be fixed with https://github.com/docker-library/official-images/pull/1711
