### ISSUE TITLE
Can your build be setup on separated instances?

### ISSUE THREAD

**Issue by patovala** [klaemo/docker-couchdb#21]
I'm trying to create a cluster with separated instances, can I use your dockerized build to talk each others?

**Comment by klaemo** [comment]
are talking about a cluster in the couchdb 2.0 sense or do you simply want to have multiple couchdb 1.6 instances?

**Comment by patovala** [comment]
Your docker build works great and delivers 3 instances by default. Now I have an extra instance but not inside that docker (not even inside the same machine), so I was hoping to get all 4 working.  Is this possible? I've tried adding bigcouch@fqdn and from inside the docker I can ping and telnet the 4th instance but they don't work as a cluster.

**Comment by klaemo** [comment]
I haven't actually played around with couchdb clusters, maybe the community can help. 
ping @janl

**Comment by klaemo** [comment]
ping @janl

**Comment by janl** [comment]
https://docs.google.com/document/d/1BtndYr-0KDQTqBSLVdJoR_8C5ObYjT1RBo_Qyh5ykdQ/edit# explains how to set up a cluster on different machines.
