### ISSUE TITLE
ssh into this docker

### ISSUE THREAD

**Issue by bertvh** [klaemo/docker-couchdb#24]
I'm probably asking a stupid question here (new to docker). Is it possible to ssh into this docker?

**Comment by klaemo** [comment]
Nope, that's not possible and it's not something your supposed to do in the docker world :) there are articles on this topic online. I'm on my phone atm and can't look them up, but you'll find it. 

---
Clemens

**Comment by bertvh** [comment]
Will do. Thanks!
