### ISSUE TITLE
Add haproxy support for 2.0

### ISSUE THREAD

**Issue by klaemo** [klaemo/docker-couchdb#30]
Apparently this is supported as of https://github.com/apache/couchdb/commit/587646f1fec6f665f70c97c24f3eef95780b409a

@kxepal what needs to be done here? do we just install haproxy inside of the container?
That kind of goes against the docker principle of only having one process per container. I don't really care, though :D

**Comment by kxepal** [comment]
Yes, looks like so. We ships default config file which will be used unless you provide your own.
As about principle...I think it doesn't matter while you boot three nodes inside single container (;
That's why it's developers preview, not ready for production solution (:
