### ISSUE TITLE
reduce docker images size

### ISSUE THREAD

**Issue by snowch** [klaemo/docker-couchdb#32]
The couchdb images is quite large (1GB).  There may be some opportunities for reducing the image size by chaining commands, e.g.

```dockerfile
RUN wget http://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_18.0-1~debian~jessie_amd64.deb \
    && dpkg -i esl-erlang_18.0-1~debian~jessie_amd64.deb \
    && rm esl-erlang_18.0-1~debian~jessie_amd64.deb
```
For more info see: https://labs.ctl.io/optimizing-docker-images/

**Comment by klaemo** [comment]
Yep, I know, but since it's "only" the dev version I didn't really care about optimizing it. It takes so damn long to test, because it involves building the whole thing over and over again :D 

I'll see what I can do. :)

The 1.6 image is heavily optimized though.

**Comment by snowch** [comment]
Ah, thanks for the update.  Btw on another note, would you be interested in configuring automated builds on Travis CI [1]?  I haven't tried this before, but it looks like it would be useful (if the travis build doesn't time out).  

[1] http://docs.travis-ci.com/user/docker/

**Comment by klaemo** [comment]
Interesting, thank you :) I'll definitely look into it

**Comment by klaemo** [comment]
I don't think TravisCI would have any advantages here. I'd much rather setup a CouchDB 2.0 automated build on Docker Hub. What do you think?

**Comment by klaemo** [comment]
cut it down to 600MB. If you know of any other improvements, let me know :)

**Comment by kxepal** [comment]
@klaemo I think you can drop with easy:
- default-jdk 
- libwxgtk3.0 
- pkg-config
- python-sphinx
-  texinfo
-  texlive-base
-  texlive-fonts-extra
-  texlive-fonts-recommended
-  texlive-latex-extra

e.g. all docs deps (`configure --disable-docs` will turn them off). I'm not sure if someone will use them with docker.

Also drop:
- git clone https://github.com/rebar/rebar /usr/src/rebar  && (cd /usr/src/rebar ; make && mv rebar /usr/local/bin/) 

configure script fetches the right rebar now and makes everything right (:

P.S. Sorry, my system doesn't support docker yet to let me make a  PR ):

**Comment by klaemo** [comment]
@kxepal someone added the doc deps in a PR here. So, maybe there is interest in it? I think I'll just make a `2.0-dev-docs` with the docs and a `2.0-dev` without them. Anyway, without the docs the image is `57 MB` lighter. Still at `557 MB` though (as a reference: 1.6.1 weighs in at around `200 MB`).

Do you know if we can remove any of the erlang packages after the build? Or anything of CouchDB's source?

Thanks for the rebar tip :)

**Comment by kxepal** [comment]
@klaemo Hm...I was expected more from docs (:

Need to check what have installed, how much it in MiBs and if it even needed to be installed. Technically, CouchDB 2.0 requires all the same deps as 1.6.1 and it codebase is indeed bigger, but not so much to be measured in dozens or hundred MiBs. Having 600 over 200 is suspicious.

**Comment by kxepal** [comment]
Got the idea: drop all the .git directories everywhere (: Also do clone --depth 1 for faster fetch. This will give you ~ -100 MiB. Another 100 MiB are in src/fauxton/node_modules - that's build artefact that not used in runtime.

So, already it's possible to cut down size to 350-400 MiBs. + some dozes certainly could be won by optimizing installed packages (not sure what is erlang-dev, erlang-eunit is needed to testing etc.)

**Comment by klaemo** [comment]
Removing .git directories and --depth 1 are great ideas. :) src/fauxton/node_modules and erlang-dev already get removed after the build.

**Comment by kxepal** [comment]
Hm...ok, I'm confused then what else uses all the remaining space /:

**Comment by klaemo** [comment]
Okay, we're down to ~398 MB. Should be enough for now. Thanks, @kxepal for your input :)

**Comment by kxepal** [comment]
Nice!

**Comment by klaemo** [comment]
This looks even better: https://hub.docker.com/r/klaemo/couchdb/tags/ o.O no idea how they got those sizes.
