### ISSUE TITLE
configuration as volume

### ISSUE THREAD

**Issue by Ti-webdev** [klaemo/docker-couchdb#34]
The settings (including admin password) will be lost then recreate containers
Please add /usr/local/etc/couchdb to volumes

**Comment by klaemo** [comment]
You could add the volume yourself at runtime with something like `docker run -v /usr/local/etc/couchdb` or even mount a host directory in that path.
But imho it's better to specify your settings at build time and add your own `local.ini` to the image. If your settings change, you simply create a new container with the new settings.

**Comment by Ti-webdev** [comment]
[Best practices for writing **Dockerfiles**](https://docs.docker.com/articles/dockerfile_best-practices/)
> The **VOLUME** instruction should be used to expose any database storage area, **configuration storage**, or files/folders created by your docker container. You are strongly encouraged to use VOLUME for any mutable and/or user-serviceable parts of your image.

**Comment by klaemo** [comment]
Interesting. I'm still curious why the other images for databases don't do it. I took a look at the official redis, Postgres and MySQL images and they don't seem to expose the config. 

---
Clemens

**Comment by Ti-webdev** [comment]
Anyway, Couchdb is different database. It can change configuration in realtime through [REST API](http://couchdb.readthedocs.org/en/1.6.1/api/server/configuration.html)
