### ISSUE TITLE
Docker Build Fails due to upgraded Erlang-dev

### ISSUE THREAD

**Issue by rajasaur** [klaemo/docker-couchdb#35]
Thanks for the Dockerfile but if I try to build it (as I needed to package local.ini with the build), it failed with the following error:
```
The following packages have unmet dependencies:
 erlang-dev : Depends: erlang-base (= 1:17.5.3) but 1:18.1 is to be installed or
                       erlang-base-hipe (= 1:17.5.3)
```

According to the CouchDB build from source, erlang-base >= 1.14 should be okay, should the Dockerfile be modified to be greater than 1.17?

Update: I managed to get what I wanted by using your image as the base and adding local.ini.

**Comment by rajasaur** [comment]
Not sure how to get a particular version as it needs every dependency in erlang spelled out if we give 1:17.5.3.. 

There is a bug that got fixed to support Erlang 18 in CouchDB. https://github.com/apache/couchdb/commit/95cb436be30305efa091809813b64ef31af968c8
This is in the 1.6.x branch but it needs pulling from git rather than downloading the source.

**Comment by klaemo** [comment]
Thanks for reporting this. 
The erlang-solutions repo is really annoying, they keep breaking old erlang versions. :( I'll lick into it.

**Comment by klaemo** [comment]
Should be fixed now. We're using debians's erlang now.
