### ISSUE TITLE
No _users database in 2.0-dev?

### ISSUE THREAD

**Issue by cquillen2003** [klaemo/docker-couchdb#38]
There is no Authentication Database (_users) showing up in Fauxton after setting up the 2.0-dev container.  Requests to /_users confirm that it does not exist.

Is there a way to create one to use CouchDB's built-in authentication mechanism?

**Comment by kxepal** [comment]
Technically, it should be created on cluster setup. Till that, indeed, it missing. The way on _users db creation is the same as for any else: `curl -XPUT /_users`, but it need to be done when you join all the nodes.

**Comment by cquillen2003** [comment]
Looks like it requires setup before _users is created.  Pressing the Setup button on the Setup page did it.

**Comment by kxepal** [comment]
Right, that's the one of the way to handle this.
