### ISSUE TITLE
CORS error after adding a user to _users database

### ISSUE THREAD

**Issue by cquillen2003** [klaemo/docker-couchdb#39]
Everything works until adding my first user to the _users database, then I get a CORS related error when trying to authenticate.

I get the error below after creating a user successfully with this standard request:
 PUT  /_users/org.couchdb.user:name

Error:
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 401.

Any help will be greatly appreciated!  I've spent all day trying to get CouchDB 2 setup.

**Comment by kxepal** [comment]
Had you followed [docs instructions](http://docs.couchdb.org/en/latest/config/http.html#cross-origin-resource-sharing)? By default CORS is disabled. May be we should revise it.

>  I've spent all day trying to get CouchDB 2 setup.

Sorry to hear that! CouchDB 2 is far long from release state, so any feedback and suggestions how to make life simpler are welcome, even oblivious ones (:

**Comment by cquillen2003** [comment]
I reviewed the docs at length.  Everything is set properly I believe.  And
Fauxton enables setting CORS, so it makes that easy.

CORS requests are working fine for me until adding a user to the _users
DB.  Very strange.  Any other ideas?  Are you able to reproduce this issue?

Maybe Fauxton's Enable-CORS script is missing something related to
authentication.


On Tuesday, November 24, 2015, Alexander Shorin <notifications@github.com>
wrote:

> Had you followed docs instructions
> <http://docs.couchdb.org/en/latest/config/http.html#cross-origin-resource-sharing>?
> By default CORS is disabled. May be we should revise it.
>
> I've spent all day trying to get CouchDB 2 setup.
>
> Sorry to hear that! CouchDB 2 is far long from release state, so any
> feedback and suggestions how to make life simpler are welcome, even
> oblivious ones (:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/klaemo/docker-couchdb/issues/39#issuecomment-159179329>
> .
>


-- 
Sent from Gmail Mobile

**Comment by kxepal** [comment]
Hm, strange indeed. Suddenly, my system is not configured to support docker, so may be others could help here. cc @robertkowalski

**Comment by cquillen2003** [comment]
I'm using Digital Ocean's one-click app for Docker to spin up a Docker
powered VM.  If you delete the VM after running the test there's
essentially no charge.  Please try to reproduce using that if you get the
chance.

BTW, Digital Ocean is by far the best platform-as-a-service (PAAS) option
for CouchDB that I've been able to find.  And CouchDB is greatly in need of
PAAS options.  Cloudant's free version has been super slow lately (up to 4
seconds per request sometimes) and their next tier is $1,800/month minimum.

**Comment by janl** [comment]
@chris-kobrzak can you share your config?

**Comment by janl** [comment]
and the error you were getting?

**Comment by klaemo** [comment]
@cquillen2003 have you tried again lately? we pushed some fixes to the 2.0-dev image.

**Comment by cquillen2003** [comment]
I haven't tried lately, but I'll report back when I do.

**Comment by cquillen2003** [comment]
@klaemo I'm trying again but the new 2.0-dev image disables the configuration menu.  I need CORS enabled to test this against my application.  Any help here will be greatly appreciated.

**Comment by janl** [comment]
You need to use `/_node/<nodename>/_config` in 2.0 where `<nodename>` is the name each of your nodes. If you have a three node closet,r you have to do it three times.

**Comment by garrensmith** [comment]
@cquillen2003 did you come right with this?

**Comment by garrensmith** [comment]
I'm closing since I think this is fixed.
