### ISSUE TITLE
Config disabled:  How to enable CORS?

### ISSUE THREAD

**Issue by cquillen2003** [klaemo/docker-couchdb#42]
The latest couchdb:2.0-dev image works nicely on Digital Ocean.  However, now the Configuration menu in Fauxton is disabled!  How do I enable it?  I need to enable CORS and specify the allowed hosts.

If it helps, I do not need a 3 node cluster.  Just a single node with CORS enabled.

IMHO, this is a major blocker as most applications will need to access CouchDB via CORS.  Also, I do not have time learn Chef, Ansible, Puppet or Salt at this point.

**Comment by klaemo** [comment]
You can try a tool like: https://www.npmjs.com/package/add-cors-to-couchdb

@janl and @robertkowalski might be able to shed some light on the config menu situation

**Comment by cquillen2003** [comment]
Thanks for getting back to me so quickly.  I tried the add-cors-to-couchdb tool but I got a 404 error.

**Comment by kxepal** [comment]
`add-cors-to-couchdb` won't work with 2.0: you need to run it against every node local port (*5986).

**Comment by cquillen2003** [comment]
@klaemo @kxepal Any idea where the local.ini file is located on Digital Ocean's VPS after pulling this image?  Maybe I can edit the file manually via the command line or FTP.

**Comment by cquillen2003** [comment]
@kxepal As far as the add-cors-to-couchdb tool goes, can you be more specific?  Will it not work with 2.0 or do I just need to run it multiple times?  If so, which ports exactly?

**Comment by kxepal** [comment]
@cquillen2003 cannot help with DO question, but for second one you'll have something like: 
```
add-cors-to-couchdb http://localhost:{15986,25986,35986} -u myusername -p mypassword
```

**Comment by cquillen2003** [comment]
@kxepal The following command results in a connection refused error:

add-cors-to-couchdb http://localhost:{15986,25986,35986} -u myusername -p mypassword

Should the ports be x5986 or x5984?  Both don't seem to work, but I'm curious why 86 instead of 84.

**Comment by cquillen2003** [comment]
@klaemo I'm still trying to get CORS enabled.  No luck yet.  Is there a way to run this image with a single node (no cluster)?  If so, I think the Configuration menu will be exposed in Fauxton by default.

**Comment by klaemo** [comment]
`docker run -it -p 15984:5984 klaemo/couchdb:2.0-dev --with-haproxy -n 1`

please familiarize yourself with the available options `docker run -it -p 15984:5984 klaemo/couchdb:2.0-dev --help`.

**Comment by janl** [comment]
CouchDB 2.0 instances come with two ports: `5984 and 5986` (for the dev cluster it is `(1|2|3|n)598(4|6)`). `5984` is the public, clustered port (e.g. requests here are handled by the cluster as opposed to just that one node) and `5986` is the “node local” port that only ever talks to that one node and doesn’t call out to other nodes to answer requests. If you squint, `5986` is roughly what you know from CouchDB 1.x.

Now on `5984`, some APIs aren’t available, because there is no way (or we haven’t put in the time) to design them to work in a clustered scenario. So for 2.0 the `5984` endpoint is losing a bunch of useful APIs, like `/_config` which you need to set things like CORS.

**The Solution** here is to use the new and 2.0-only api `/_node/ on port `5984`. The format is:

`GET | PUT | DELETE /_node/nodename@host/_config/section/value`

`nodename@host` is your `rel/vm.args` configuration. You can look up the node names in `:5984/_membership` from a running cluster. In a three node cluster, you need to call the above URL three times, each with the respective node names in the URL to set a node’s configuration.

A patch for `add-cors-to-couchdb` would be:

- see if the CouchDB instance returns a non-404 on `/_membership`
- if not, use existing behaviour. If yes, continue:
- read `/_membership` result.

The format looks something like this:

```JS
{
  "all_nodes": ["couchdb@10.0.0.121","couchdb@10.0.0.122","couchdb@10.0.0.123"],
  "cluster_nodes":["couchdb@10.0.0.121","couchdb@10.0.0.122","couchdb@10.0.0.123"]
}
```

- for each entry in `cluster_nodes`, call the `/_node/nodename@host/_config/section/value` URL
  - if any of the requests fail, the code should try re-try, or to undo the change on the nodes where it worked, to avoid an inconsistent cluster. This lack of transaction semantics is what kept us from adding `/_config` to `5984` in 2.0 so far.
- Done.

**Comment by kxepal** [comment]
@cquillen2003 they should be x5986 since good old config is not available on cluster port x5984. Well, actually it is, but I'm not sure that add-cors-to-couchdb will handle it. Just for fun try:
```
add-cors-to-couchdb http://yourserver:15984/_node/node1@127.0.0.1/ -u myusername -p mypassword
```
Increment port and node numbers respectively.

**Comment by cquillen2003** [comment]
@klaemo Thanks for the info.  And I'll certainly look at the configuration options.

Unfortunately, trying to set n = 1 resulted in the following error:

root@couchdb-2:~# docker run -it -p 5984:5984 klaemo/couchdb:2.0-dev --with-haproxy -n 1
[ * ] Setup environment ... ok
[ * ] Ensure CouchDB is built ... ok
[ * ] Prepare configuration files ... ok
[ * ] Start node node1 ... ok
[ * ] Check node at http://127.0.0.1:15984/ ... failed: [Errno socket error] [Errno 111] Connection refused
[ * ] Check node at http://127.0.0.1:15984/ ... ok
[ * ] Running cluster setup ... failed: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/src/couchdb/dev/run", line 535, in <module>
    main()
  File "/usr/src/couchdb/dev/run", line 73, in main
    startup(ctx)
  File "/usr/src/couchdb/dev/run", line 307, in startup
    cluster_setup(ctx)
  File "/usr/src/couchdb/dev/run", line 57, in wrapper
    res = func(*args, **kwargs)
  File "/usr/src/couchdb/dev/run", line 398, in cluster_setup
    finish_cluster(lead_port, *ctx['admin'])
  File "/usr/src/couchdb/dev/run", line 452, in finish_cluster
    'Content-Type': 'application/json'})
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

**Comment by cquillen2003** [comment]
@janl Thanks for the info.  I was able to get CORS setup using Curl and the /_node/nodename@host/_config/section/value end-points you mentioned above.

As an aside, IMHO CouchDB should come with CORS enabled by default.  CouchDB is a great DB for single page apps (with or without PouchDB) but most of these apps are not going to be served directly from CouchDB (as a CouchApp).  So why not remove this hurdle to get up and running?

**Comment by DimShadoWWW** [comment]
Hello, I tried to enable CORS in couchdb adding a new local.ini to the path /usr/src/couchdb/rel/overlay/etc/local.ini. It included
```
[httpd]
enable_cors = true

[cors]
credentials = true
```
that local.ini was copied to the nodes before they start, but it didn't work... CORS wasn't working, my local pouchdb couldn't do replicate. This method should work, right??

Later I used the  /_node/nodename@host/_config/section/value end-points to enable CORS this way:
```shell
for node in "node1" "node2" "node3";do
  echo Enabling CORS in node $node
  curl -sX PUT "$ADMIN_HOST_URL/_node/${node}@127.0.0.1/_config/httpd/enable_cors" -d '"true"' 1>/dev/null
  echo -n .
  curl -sX PUT "$ADMIN_HOST_URL/_node/${node}@127.0.0.1/_config/cors/origins" -d '"*"' 1>/dev/null
  echo -n .
  curl -sX PUT "$ADMIN_HOST_URL/_node/${node}@127.0.0.1/_config/cors/credentials" -d '"true"' 1>/dev/null
  echo -n .
  curl -sX PUT "$ADMIN_HOST_URL/_node/${node}@127.0.0.1/_config/cors/methods" -d '"GET, PUT, POST, HEAD, DELETE"' 1>/dev/null
  echo -n .
  curl -sX PUT "$ADMIN_HOST_URL/_node/${node}@127.0.0.1/_config/cors/headers" -d '"accept, authorization, content-type, origin, referer, x-csrf-token"' 1>/dev/null
  echo .
done
```

Now pouchdb can replicate and update the remote couchdb (before enable CORS it couldn't do it), but it keep showing the message:
```
PouchDB: the remote database may not have CORS enabled.If not please enable CORS: http://pouchdb.com/errors.html#no_access_control_allow_origin_header
```
There is anything else to do?

**Comment by klaemo** [comment]
`add-cors-to-couchdb` has been updated to support CouchDB 2.0 https://github.com/pouchdb/add-cors-to-couchdb

**Comment by cquillen2003** [comment]
I'm closing this issue because I have been able to configure CORS on cluster just by using CURL and hitting each node on the cluster.  Feels redundant, but it works.
