### ISSUE TITLE
Allow configuration of admin user and password via environment vars

### ISSUE THREAD

**Issue by bripkens** [klaemo/docker-couchdb#43]
Many official Docker images (and it looks like this Docker image is going to become the official Docker image for couchdb) support the definition of the admin user name and password via environment vars, e.g. [MySQL](https://hub.docker.com/_/mysql/). It would be great if this image would support this as well.

**Comment by klaemo** [comment]
I'd be open to that, even though it is freakishly simple to create an admin user for CouchDB in different ways. `local.ini`, REST API, Fauxton...

But in order to align with other DBs and make this common configuration task a littler simpler, it is something to consider. :)

**Comment by bripkens** [comment]
I am only writing this because you have the following in the description of the `2.0-dev` [container description](https://github.com/klaemo/docker-couchdb#run-dev):

```
…
Admin username: root
Password: 37l7YDQJ
…
```

Being able to describe credentials via env args would make it incredibly easy to bring up CouchDB for dev purposes (as it would only be a one liner) :).

**Comment by klaemo** [comment]
Oh in the case of 2.0 you can do `docker run -it -p 5984:5984 klaemo/couchdb:2.0-dev --with-haproxy --admin=USER:PASS` to set the admin user :) Does that help?

Check out `docker run -it -p 5984:5984 klaemo/couchdb:2.0-dev --help` for all available options.

**Comment by bripkens** [comment]
Yes, that will help. Danke Clemens :)

**Comment by jakobrosenberg** [comment]
Sometimes environment vars are your only option. Ie. if you use couchdb in Kitematic.

**Comment by klaemo** [comment]
Thanks for the feedback @jakobrosenberg. It's on my list :)

**Comment by klaemo** [comment]
fixed by #46. will land in the official image soon :)
