### ISSUE TITLE
Erlang Version in Debian (again)

### ISSUE THREAD

**Issue by klaemo** [klaemo/docker-couchdb#50]
@janl would you mind taking a look at jessie's erlang changelog [1] to see if they applied the necessary patch for 17.3?

If not, how do we get a known-good erlang version?

[1] http://metadata.ftp-master.debian.org/changelogs/main/e/erlang/erlang_17.3-dfsg-4_changelog

**Comment by kxepal** [comment]
@klaemo I was planned to write the issue about 17.3 Erlang - it badly known as the release with broken SSL/TLS handshake. I feel that debian applied all the required patches on top of it, but still users may be confused about. 17.5 or 18.2 are the good ones to use.

**Comment by klaemo** [comment]
Does 18.2 work for CouchDB 1.6.x?

**Comment by kxepal** [comment]
No, 1.6.x  supports <=17.x

**Comment by dch** [comment]
@klaemo we do have a patch for 18.x support see https://github.com/apache/couchdb/commit/95cb436 let me know if you need any help with it

**Comment by dch** [comment]
I think we will be better off in general using erlang-solutions packages

**Comment by klaemo** [comment]
@dch Is it possible to specifically install erlang 17.5 from erlang-solutions? I know I can do something like `apt-get install erlang-nox=1:17.5-xyz`, but I've had trouble in the past because some of the erlang packages depended on the latest erlang instead. It was confusing and I gave up :D

**Comment by janl** [comment]
@klaemo Debian’s 17.3 looks good to me.

**Comment by klaemo** [comment]
Cool, thanks @janl. Do you think we should add a note about it to the Readme? Saying it's 17.3 but patched?

**Comment by janl** [comment]
@klaemo yeah, why not :)

**Comment by klaemo** [comment]
https://github.com/docker-library/official-images/pull/1711
