### ISSUE TITLE
/docker-entrypoint.sh: line 35: printf: `p': invalid format character

### ISSUE THREAD

**Issue by aeharding** [klaemo/docker-couchdb#60]
This is due to interpolating the environment variables for username and password directly within the printf body, and not as %s params.

**Comment by aeharding** [comment]
To reproduce, try a password like "hello%^world".

See my PR for a fix.

Thanks for your work and continued maintenance to these docker images.

**Comment by klaemo** [comment]
fixed in #61 
Thanks for the issue and PR :)

**Comment by klaemo** [comment]
it will take a while to land in the official image, but you should be able to use it with the `klaemo/couchdb` image

**Comment by aeharding** [comment]
🍻 Cheers, thanks for the quick response!
