### ISSUE TITLE
SSL with CouchDB 2.0?

### ISSUE THREAD

**Issue by cquillen2003** [klaemo/docker-couchdb#62]
I need a CouchDB 2.0 instance with SSL support.  Is this doable with CouchDB's native SSL support and the 2.0-single image?

I see the dedicated image for couchdb-ssl that uses Nginx.  Is CouchDB's native SSL support so bad that I'll need to wait for an Nginx solution for CouchDB 2.0?

**Comment by klaemo** [comment]
there are multiple options. reverse proxies in front of couchdb or built-in SSL...both should work just fine. you could ask in #couchdb on IRC regarding the quality of the built-in SSL support

**Comment by cquillen2003** [comment]
@klaemo Okay, thank you.  It sounds like using a reverse proxy is the way to go:

[](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=48203146)

Do you have any plans to create a dockerized CouchDB 2.0 with SSL support?  I'd really like to have an A+ rated CouchDB 2 server, but I'm not sure I trust my sys admin skills to pull it off in a timely manner.
