### ISSUE TITLE
Command to run 2.0-single with no existing database directory?

### ISSUE THREAD

**Issue by cquillen2003** [klaemo/docker-couchdb#63]
The docs only give the command to run 2.0-single and "use your current directory as the CouchDB database directory".  I'm simply trying to spin up a new instance with no data on Digital Ocean, but the following command fails:

docker run -p 5984:5984 klaemo/couchdb:2.0-single

What command should I use to start up a fresh instance with no exiting data?

**Comment by cquillen2003** [comment]
Tried 2.0-single again on Digital Ocean and got the same error.

Steps to reproduce:
-Digital Ocean - Create Droplet
-Choose an image - One-click Apps - Docker 1.11.2 on 14.04
-ssh root@[Droplet IP Address]
-docker pull klaemo/couchdb:2.0-single
-docker run -p 5984:5984 klaemo/couchdb:2.0-single

Result:

20:15:31.611 [info] Application lager started on node nonode@nohost
20:15:31.611 [info] Application couch_log_lager started on node nonode@nohost
20:15:31.611 [info] Application couch_mrview started on node nonode@nohost
20:15:31.611 [info] Application couch_plugins started on node nonode@nohost
20:15:31.616 [info] open_result error {not_found,no_db_file} for _replicator
20:15:31.622 [notice] creating replicator ddoc
20:15:31.630 [info] Application couch_replicator started on node nonode@nohost
20:15:31.630 [info] Application couch_peruser started on node nonode@nohost
20:15:31.635 [info] Application ddoc_cache started on node nonode@nohost
20:15:31.650 [info] Application global_changes started on node nonode@nohost
20:15:31.650 [info] Application jiffy started on node nonode@nohost
20:15:31.656 [info] Application mango started on node nonode@nohost
20:15:31.662 [info] Application setup started on node nonode@nohost
20:15:31.662 [info] Application snappy started on node nonode@nohost
20:15:36.535 [error] gen_server chttpd_auth_cache terminated with reason: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,325}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,313}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,329}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,184}]},...]}
20:15:36.535 [error] CRASH REPORT Process chttpd_auth_cache with 0 neighbours exited with reason: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,325}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,313}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,329}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,184}]},...]} in gen_server:terminate/6 line 737
20:15:36.536 [error] Supervisor chttpd_sup had child chttpd_auth_cache started with chttpd_auth_cache:start_link() at <0.310.0> exit with reason {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,325}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,313}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,329}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,184}]},...]} in context child_terminated
.
.
.

**Comment by klaemo** [comment]
> Single Node Setup
When you click “Single-Node-Setup”, you will get asked for an admin username and password. Choose them well and remember them. You can also bind CouchDB to a public port, so it is accessible within your LAN or the public, if you are doing this on a public VM.
When you run 2.0 as a single node, it doesn’t create system databases on startup. You have to do this manually. For example:
`curl -X PUT http://127.0.0.1:5984/_users`

from https://docs.google.com/document/d/1BtndYr-0KDQTqBSLVdJoR_8C5ObYjT1RBo_Qyh5ykdQ

**Comment by cquillen2003** [comment]
@klaemo Thank you for the response.  Do I create the users database before running `docker run -p 5984:5984 klaemo/couchdb:2.0-single`?

I am getting the above error just trying to run this command, before clicking "Single Node Setup" or anything else.

**Comment by klaemo** [comment]
you can do it whenever. probably before "Single Node Setup" is a good time.
