### ISSUE TITLE
How access the etc directory?

### ISSUE THREAD

**Issue by rolfn** [klaemo/docker-couchdb#67]
How can I make `/opt/couchdb/etc` accessible from outside of the docker container? I tried
```
/usr/bin/docker run ... -v /etc/couchdb_docker:/opt/couchdb/etc
```
with the two files `local.ini` and `vm.args` inside of the host directory. This doesn't work because CouchDB seems to need also a (self-created) `default.ini` at this place. I created such a file and then it works. But I suppose a better solution should be exist.

...Rolf

**Comment by klaemo** [comment]
As of `2.0-rc4` you can and should put your custom config files in `couchdb/etc/local.d`

```
docker run ... -v /etc/couchdb_docker:/opt/couchdb/etc/local.d
```

That way `default.ini` doesn't get overwritten. Let me know if this solves your problem.

**Comment by rolfn** [comment]
You say: That way default.ini doesn't get overwritten. This is true. But docker doesn't start, because  `default.ini` does not exist in the mounted host directory (unless I put it in). See the other issue ("Permissions problem #65"). This is a "chicken or egg dilemma" ;-)
