### ISSUE TITLE
require_valid_user is ignored

### ISSUE THREAD

**Issue by tfpereira** [klaemo/docker-couchdb#68]
I'm running a 2.0-single instance with the following Dockerfile:

```
FROM klaemo/couchdb:2.0-single
USER root
RUN echo 'couchdb:x:99:99:couchdb:/:/bin/sh' >> /etc/passwd
USER couchdb
COPY local.ini /opt/couchdb/etc/local.ini
ENTRYPOINT ["/opt/couchdb/bin/couchdb"]
```

The local.ini is as follows:

```
; CouchDB Configuration Settings

; Custom settings should be made in this file. They will override settings
; in default.ini, but unlike changes made to default.ini, this file won't be
; overwritten on server upgrade.

[chttpd]
bind_address = 0.0.0.0
port = 5984

[couchdb]
uuid = theuuid

[admins]
root = thehashedpassword

[couch_httpd_auth]
require_valid_user = true
secret = thesecret
```

When the CouchDB instance runs, I can see on Fauxton that require_valid_user is recognized has being true, However, anonymous users still have access to the database.

Anything I might be missing here?

**Comment by klaemo** [comment]
could you try if it works with `2.0-rc3` and if not it's probably a CouchDB 2.0 bug and worth reporting to them :)

**Comment by tfpereira** [comment]
Tried replacing 2.0-single for 2.0-rc3, the problem persists. Guess I should report it to them. Thanks :)

**Comment by tfpereira** [comment]
In case someone wonders into this, there is no bug on CouchDB. I explained on JIRA and shall explain here:

 In my configuration, I was using port 5984 which was the chttpd port. I was applying all my permissions on [couch_httpd_auth], which was running on port 5986.
Changing my local.ini to
```
[chttpd]
bind_address = 127.0.0.1
port = 5984
[httpd]
bind_address = 0.0.0.0
port = 5986
[couchdb]
uuid = myuuid
[admins]
root = mypassword
[couch_httpd_auth]
require_valid_user = true
secret = mysecret
```
And pointing to port 5986 resolved the issue.

**Comment by klaemo** [comment]
Thanks for the follow up :) This is really helpful!

---
Clemens
