### ISSUE TITLE
Access the couchdb directory for config purposes?

### ISSUE THREAD

**Issue by cquillen2003** [klaemo/docker-couchdb#70]
Is it possible to access the couchdb directory on an existing couchdb:2.0-dev instance?

I've successfully installed couchdb:2.0-dev on Digital Ocean, but I can't find the couchdb directory on the server.  I would like to edit the local.ini file and add an SSL cert to enable HTTPS.  Any help will be greatly appreciated.

Thanks.

**Comment by dholth** [comment]
You could do something like `docker exec -it couchdb /bin/bash` to get a shell inside the container named `couchdb`.

You could set up volumes on an initial run, but these tend to shadow the out-of-the-box configuration. `docker run -d -p 5984:5984 -v $(pwd)/data:/opt/couchdb/data -v $(pwd)/etc:/opt/couchdb/etc --name couchdb2 klaemo/couchdb:2.0.0-rc1-vote`

You could type `mount` inside the countainer, look for a line that says something like `/dev/mapper/docker-253:0-38315740-dc697e07822feeface64c9a6637dfe7089ca27e37f75c77b5cd0578eb8d6a3dd on / type xfs`, and then in the host run `mkdir /mnt/couchdb` ; `mount /dev/mapper/docker-253:0-38315740-dc697e07822feeface64c9a6637dfe7089ca27e37f75c77b5cd0578eb8d6a3dd /mnt/couchdb`

**Comment by garrensmith** [comment]
Did this work?

I'm going to close this ticket. Open it again if you need more help
