### ISSUE TITLE
Single Node Setup?

### ISSUE THREAD

**Issue by cquillen2003** [klaemo/docker-couchdb#71]
I've tried running 2.0-rc4 10+ times, with NO luck.  Please help.

The instructions say "so you will have to create _global_changes, _metadata, _replicator and _users manually".  How do I do that before CouchDB is running?

The "Single Node Setup" section of "The CouchDB 2.0 Release Testing Plan" does not help, because I can't "click Single-Node-Setup" or use CURL because CouchDB is not even running yet!

**Comment by dholth** [comment]
CouchDB should run once `docker run` or `docker start`, and Fauxton even kinda works under `_util`, but you may `curl -X PUT http://localhost:5984/_users` etc. to create those databases.

**Comment by nireak** [comment]
The new version "2.0.0" does not ends immediately (like the one you tried) but enters a warning loop allowing you to type in another terminal the command "curl -X PUT http://localhost:5984/_users"

**Comment by garrensmith** [comment]
Could you test again. I was able to create a single node cluster with:

` docker run -p 5984:5984 klaemo/couchdb:2.0`.
 I could then access fauxton:
`http://127.0.0.1:5984/_utils` and then configure it into a single node cluster.

I'm going to close this ticket but open it again if you cannot do the same.
