### ISSUE TITLE
Config endpoint not available in single node setup

### ISSUE THREAD

**Issue by alexcriss** [klaemo/docker-couchdb#72]
Hi all,

I am trying to use the _config API to manage a single node setup that is based on the 2.0-single image (almost same Dockerfile, just using a debian image for a raspberry pi and configure with --disable-fauxton since the pi goes out of memory when building it). The container is run with:
```
docker run -p 20011:5984
```
If I try to query the _config API I get:
```
[root@pi-server 2.0-single]# curl -X GET http://127.0.0.1:20010/_config
{"error":"not_found","reason":"Database does not exist."}
```

I also cannot use Fauxton to configure the node, since I did not compile it. Is there any way to get the _config endpoint available, or should I modify the local.ini file when creating the image?

Thanks a lot,
Ale

**Comment by klaemo** [comment]
Maybe [this comment](https://github.com/klaemo/docker-couchdb/issues/42#issuecomment-169610897) sheds some light on this.

**Comment by alexcriss** [comment]
Lovely, it works! Thanks so much for the impressive response time :)
