### ISSUE TITLE
stable shows github commit hash instead version number

### ISSUE THREAD

**Issue by mikeymckay** [klaemo/docker-couchdb#73]
When asking CouchDB to report its version # it returns the github commit hash. It would be much better to show the normal version number, e.g. 1.6.1

{
"couchdb": "Welcome",
"version": "1df597f",
"vendor": {
"name": "The Apache Software Foundation"
}
}

**Comment by klaemo** [comment]
Is this an issue with this docker image? I don't know if we can influence the output of CouchDB. 

---
Clemens

**Comment by mikeymckay** [comment]
I believe it's an issue with the docker image. A previous deployment of
this docker image returns the expected version:

{"couchdb":"Welcome","uuid":"26fcd8d0febbe477cf7a33895b6b1e5a","version":"1.6.1","vendor":{"name":"The
Apache Software Foundation","version":"1.6.1"}}

**Comment by klaemo** [comment]
`docker run -it --rm -p 5984:5984 couchdb:1.6.1` gave me 
```
{"couchdb":"Welcome","uuid":"4e02ef6f8b2a53eaf24ea13433a18890","version":"1.6.1","vendor":{"version":"1.6.1","name":"The Apache Software Foundation"}}
```

With which version/image do you see the issue?

**Comment by mikeymckay** [comment]
Here's the command that we used:

docker pull klaemo/couchdb:latest

I am guessing that we should have used "stable"?

**Comment by mikeymckay** [comment]
Ok - looks like the error was in using latest. Thanks for your feedback - we've solved it.
