### ISSUE TITLE
Split apt-get and compile CouchDB into two RUN commands

### ISSUE THREAD

**Issue by dholth** [klaemo/docker-couchdb#76]
It takes a relatively long time to apt-get all the build dependencies. If the CouchDB build fails for any reason, we have to do that again.

Instead, `# Acquire CouchDB source code` should have its own RUN command, including `npm install -g grunt-cli`. Then Docker will cache the result of apt-get. If the compilation step needs to be attempted or changed then it will start right away.

**Comment by dholth** [comment]
Or, would this negatively affect the size of the final image?

**Comment by dholth** [comment]
Meh, turns out doing this makes a large image. One layer contains the build dependencies and the next layer removes them, but they are still using space. For this kind of quick rebuild feature you might have to copy /opt/couchdb from a build docker into a deploy docker or flatten the image.

**Comment by dholth** [comment]
It would need to do something like this instead, with a separate dockerfile for build. https://www.fpcomplete.com/blog/2015/12/docker-split-images

**Comment by klaemo** [comment]
yep, docker layering is a blessing and a curse ;)
