### ISSUE TITLE
cannot configure a cluster with multiples "latest" containers

### ISSUE THREAD

**Issue by jbtrystram** [klaemo/docker-couchdb#83]
I tried to follow the documentation [1] to create a multiple containers clusters but did not succeed. 
The setup loooks like it works but i don't see other nodes when polling `_membership`.

I could not understand how you did it in the `2.0-dev` image. It looks like it's done in the `/usr/src/couchdb/dev/run` pythn script but i could not figure out where the nodes and the cluster is declared. 
Thanks if you can give me a bit of light :) 

[1] : http://docs.couchdb.org/en/2.0.0/cluster/setup.html#the-cluster-setup-wizard

**Comment by klaemo** [comment]
Hey,
you are right, the `2.0-dev` image uses the python script that the CouchDB developers created for testing purposes. Unfortunately, I'm completely unfamiliar with 2.0's cluster config. Maybe @robertkowalski or anyone from CouchDB could help out here?

**Comment by garrensmith** [comment]
I'm closing this. The 2.0-dev will automatically configure a 3 node cluster. You can override that by doing something like this:

`docker run -p 5984:5984 klaemo/couchdb:2.0-dev --no-join`

But you will need to expose each nodes ports and then configure them. It would be better to use the 
`2.0` image as its a single node.
