### ISSUE TITLE
Restarting CouchDB 1.6.1 inside Docker loses sessions

### ISSUE THREAD

**Issue by aeharding** [klaemo/docker-couchdb#84]
Hello,

I'm using this image with CouchDB 1.6.1.

When I restart the image, I have database records persisted, but I seem to be logged out (my session is not preserved).

When running CouchDB natively on my machine, restarting preserves sessions.

If it is possible to preserve sessions across restarts? If so, is it a simple directory that I need to make a volume (along with the current directory `/usr/local/var/lib/couchdb`)?

Would it make sense to make a PR to make this default functionality (add the volume directory) if this is so?

Thank you!
Alex

**Comment by klaemo** [comment]
Which session handler do you use? Cookies or something else?

**Comment by aeharding** [comment]
I use cookies. Proxied via nginx.

**Comment by klaemo** [comment]
Hm, I can't seem to be able to reproduce. Here's what I did:

```
docker run -d --name couch -p 5984:5984 -v $(pwd)/data:/usr/local/var/lib/couchdb couchdb
# create admin and login
docker stop couch
docker start couch
# still logged in
```

**Comment by aeharding** [comment]
Hmm, maybe I need to [set the secret](http://docs.couchdb.org/en/2.0.0/config/auth.html#couch_httpd_auth/secret)?

Still weird that a plain couchdb docker container persists on restart, but mine doesn't. This is my couchdb ini file:
```
[couchdb]
max_dbs_open = 1000
max_document_size = 1000000 ; 1 MB


[couch_httpd_auth]
allow_persistent_cookies = true
timeout = 604800 ; one week session expiry
iterations = 100000 ; https://cryptosense.com/parameter-choice-for-pbkdf2/
```

I'll look into this more later. Thanks again for the quick response, @klaemo (feel free to close this until I get more solid data on what's happening).

**Comment by klaemo** [comment]
Hm, the settings look good. Weird! I'm too tired to look into this more. Let me know if you find something.

**Comment by aeharding** [comment]
Did some more research

Here's my Dockerfile:
```
FROM klaemo/couchdb:1

COPY local.ini /usr/local/etc/couchdb/
```

Did some inspection on the live docker container.

Here's `/usr/local/etc/couchdb/local.d/docker.ini`:

```
[admins]
myadmin = (redacted)

[couchdb]
uuid = (redacted)

[couch_httpd_auth]
secret = (redacted)
```

It's weird since docker-couchdb only adds the admin section to docker.ini, AFAIK.

Ugh. I'll just try inlining the secret in my local.ini... That'll probably work.

**Comment by aeharding** [comment]
New twist: It worked! Kinda. Since the admin set via environment variable gets a new hash each time (couchdb takes plaintext and computes `-pbkdf2-`, which is not the same each time), and the cookie is based off of SHA1(secret + username + passwordhash), the admin cookie will not be valid.

However, since those in the `_user` table have their `-pbkdf2-` hash persisted, they stay logged in!

Just documenting this in case someone stumbles upon the same issue. 🙂

**Comment by garrensmith** [comment]
Kamino closed and cloned this issue to apache/couchdb-docker
