### ISSUE TITLE
Understanding how to run a cluster

### ISSUE THREAD

**Issue by andywenk** [klaemo/docker-couchdb#93]
Hi @klaemo ,

first of all thanks for the great work. Highly appreciated.

### My target

I am preparing a talk for CouchDB 2.0. Beside all the hot new shit, I want to setup a cluster n=3. So my idea is to use [klaemo/couchdb](https://hub.docker.com/r/klaemo/couchdb/) and start three containers each with one CouchDB. Unfortunately I am not a super docker hero and need some help.

### Status

I am working on Mac and have docker running with DockerApp. I pulled klaemo/couchdb:latest. Then I read in the docu, that I can start couchdb with:

    docker run -p 5984:5984 -v $(pwd):/opt/couchdb/data klaemo/couchdb:2.0-single

Hm - why not klaemo/couchdb:latest I thought. But anyway. I ran the command, and, as expected, the image tag 2.0-single was pulled and started (there was an error in the logs but I leave that for later). 

Then I thought ok why not use the fresh new latest tag. That did not work because of many permission errors.

    docker run -p 5984:5984 -v $(pwd):/opt/couchdb/data klaemo/couchdb:latest
    chown: changing ownership of '/opt/couchdb/data/.CFUserTextEncoding': Permission denied
    chown: changing ownership of '/opt/couchdb/data/.cocoapods/repos/master/.git/objects/pack/pack-eec33604f65199a2ff43b17547f6b07cf056404d.idx': Permission denied
    chown: changing ownership of '/opt/couchdb/data/.cocoapods/repos/master/.git/objects/pack/pack-eec33604f65199a2ff43b17547f6b07cf056404d.pack': Permission denied
    chown: changing ownership of '/opt/couchdb/data/.cpan/build/common-sense-3.72-mT74Q2/blib/arch/.exists': Permission denied

docker ps says:

    $ docker ps
    CONTAINER ID        IMAGE                   COMMAND                  CREATED              STATUS              PORTS                                        NAMES
    bc798e515489        klaemo/couchdb:latest   "tini -- /docker-entr"   About a minute ago   Up About a minute   4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp   evil_austin

### Questions

* What am I doing wrong or what do I misunderstand? Or, is it a documentation bug?
* How would I have to setup three nodes? Can I simply run the above command three times?

Thank you very much for your assistance.

All the best 

Andy

**Comment by klaemo** [comment]
Hi Andy,
the documentation was (is) indeed confusing. Sorry about that. You should just be able to use  `klaemo/couchdb` (which is `latest` by convention). The `-single` image is deprecated. 

Also, you should be able to avoid the permission problems, if you create and mount an empty `couchdb` directory. You aren't required to mount the data volume though.

```
docker run -p 5984:5984 -v $(pwd)/couchdb:/opt/couchdb/data klaemo/couchdb:latest
```

The easiest way of running a cluster for illustration purposes is using the `klaemo/couchdb:2.0-dev` variant of the image. It will start a 3 node cluster for you.

```
docker run -p 5984:5984 klaemo/couchdb:2.0-dev
```

I hope that helped a little. If you have any further questions, let me know.

**Comment by andywenk** [comment]
Hi Clemens,

thanks a lot for your answer - highly appreciated. I am aware of the dev/run cluster locally (I have tested it as we started to merge the cluster possibilities into CouchDB). But I would like to demonstrate the cluster setup in a more "real" environment. So can you show how to setup three independent docker couch nodes? I would like to have three nodes with three different IP addresses I can put into the setup in Fauxton ...

Thanks so much 

Andy

**Comment by klaemo** [comment]
Just guessing here, but what if you start multiple containers on different ports:

```
docker run -d -p 5984:5984 klaemo/couchdb:2.0.0
docker run -d -p 5985:5984 klaemo/couchdb:2.0.0
```

I apologize that I can't be of more help here, but I'm totally unfamiliar with CouchDB's new cluster features :-/

**Comment by andywenk** [comment]
thanks @klaemo I will give it a try. Meanwhile (because I needed a solution), we created a Vagrant Box with three nodes in it ;-) https://github.com/sumcumo/couch-vagrant (alpha and still WIP)

**Comment by romainrbr** [comment]
Hi @andywenk ,

Since https://github.com/klaemo/docker-couchdb/pull/82 was accepted, you should be able to create a cluster easily:

1. On each machine, run something like : docker run -d -p 5984:5984 -p 4369:4369 -p 9100:9100 --name couchdb -e "nodename=$HOSTNAME" klaemo/couchdb:2.0-single

2. Set the same password for each node (either through the GUI or with calls)

3. Configure the cluster (again, GUI or calls)

4. Verify that everything is ok on ipofyourfirstcluster:5984:/_membership

**Comment by andywenk** [comment]
Hi @romainrbr,

oh thanks for the info. One question: what do you mean with 

> 1. On each machine ...

? I am on *one machine* (my Mac OS X laptop) and would like to create three independent CouchDB's as Docker boxes here. 

All the best

Andy

**Comment by romainrbr** [comment]
I'm not sure you can run multiple nodes locally on the same IP. (I think there is some erlang communication)
However, you won't have any issue running each node in a vagrant machine with a dedicated IP.

Just make sure to pull the latest image.

**Comment by andywenk** [comment]
@romainrbr ok - so yeah that is what we did ... see above (couch-vagrant)

**Comment by peanutpi** [comment]
Hi, @andywenk there are some recemendded changes that are needed in this docker image to run it as cluster

like in [vm.args](https://github.com/DreamworldSolutions/docker-couchdb/commit/95883921775cdf50aff7f132d3caa759a6629418) & [docker-entrypoint.sh](https://github.com/DreamworldSolutions/docker-couchdb/commit/d80ee26dd16b6d9ca8021251ae5cb2942fbbcc37)

what you can do is following 

Build a new image from these repo: https://github.com/DreamworldSolutions/docker-couchdb

following is the docker-compose.yml with load balancing

```yml
version: '2'
services:
  couchdb1:
    image: newBuiltImage/couchdb:2.0.0
    environment:
    - NODENAME=couchdb1
  couchdb2:
    image: newBuiltImage/couchdb:2.0.0
    environment:
    - NODENAME=couchdb2
  couchdb3:
    image: newBuiltImage/couchdb:2.0.0
    environment:
    - NODENAME=couchdb3
  haproxy:
    image: haproxy:1.7.3
    volumes:
    - ./haproxy:/usr/local/etc/haproxy
    ports:
    - "5984:5984"
```

- following is the haproxy config

```
global
        maxconn 512
        spread-checks 5
        log 127.0.0.1 local0

defaults
        mode http
        log global
        monitor-uri /_haproxy_health_check
        option log-health-checks
        option httplog
        balance roundrobin
        option forwardfor
        option redispatch
        retries 4
        option http-server-close
        timeout client 150000
        timeout server 3600000
        timeout connect 500

        stats enable
        stats scope .
        stats uri /_stats

frontend http-in
         # This requires HAProxy 1.5.x
         # bind *:$HAPROXY_PORT
         bind *:5984
         default_backend couchdbs

backend couchdbs
        log global
        option httpchk GET /_up
        http-check disable-on-404
        server couchdb1 couchdb1:5984 check inter 5s
        server couchdb2 couchdb2:5984 check inter 5s
        server couchdb3 couchdb3:5984 check inter 5s
```

Execute following command from your terminal

Assume that 
**couchdb1** container has ip `172.18.0.5`
**couchdb2** container has ip `172.18.0.4`
**couchdb3** container has ip `172.18.0.2`

```
curl -X POST -H "Content-Type: application/json" http://172.18.0.5:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"admin123"}'
curl -X POST -H "Content-Type: application/json" http://172.18.0.4:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"admin123"}'
curl -X POST -H "Content-Type: application/json" http://172.18.0.2:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"admin123"}'

curl -X POST -H "Content-Type: application/json" http://admin:admin123@172.18.0.5:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"admin123", "port": 5984, "remote_node": "couchdb3", "remote_current_user": "admin", "remote_current_password": "admin123" }'

curl -X POST -H "Content-Type: application/json" http://admin:admin123@172.18.0.5:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"admin123", "port": 5984, "remote_node": "couchdb2", "remote_current_user": "admin", "remote_current_password": "admin123" }'


curl -X POST -H "Content-Type: application/json" http://admin:admin123@172.18.0.5:5984/_cluster_setup -d '{"action": "add_node", "host":"couchdb2", "port": "5984", "username": "admin", "password":"admin123"}'

curl -X POST -H "Content-Type: application/json" http://admin:admin123@172.18.0.5:5984/_cluster_setup -d '{"action": "add_node", "host":"couchdb3", "port": "5984", "username": "admin", "password":"admin123"}'


curl -X POST -H "Content-Type: application/json" http://admin:admin123@172.18.0.5:5984/_cluster_setup -d '{"action": "finish_cluster"}'

curl -X GET -H "Content-Type: application/json" http://admin:admin123@172.18.0.5:5984/_membership
```

- Your cluster is ready. or if you don't want to update the image you have to assign each couchdb service fix IP in docker-compose

**Comment by andywenk** [comment]
@peanutpi thanks a lot for the info. Awesome! I will it a try asap ...

**Comment by garrensmith** [comment]
@peanutpi we moving the repo to https://github.com/apache/couchdb-docker
Would you be interested in supplying a PR to make it easier to build a compose cluster with the official docker repo?

**Comment by garrensmith** [comment]
Moved to https://github.com/apache/couchdb-docker/issues/9

**Comment by redgeoff** [comment]
Based on @peanutpi's [awesome answer](https://github.com/klaemo/docker-couchdb/issues/93#issuecomment-284704181), I've managed to [get a cluster up and running with docker-compose](https://github.com/redgeoff/couchdb-docker/tree/production-multi-node#run-cluster-via-docker-compose-wip). The issue I'm stuck on now is that the [user sessions don't appear to be replicating across nodes](http://stackoverflow.com/q/43958527/2831606).

**Comment by peanutpi** [comment]
@redgeoff : Hi I forgot to mention about the session issue. You can configure it in Haproxy. In the above configuration I forgot to add that configuration. You've to configure a session cookie based routing policy in haproxy configuration. 

You can read it here : http://www.haproxy.com/blog/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know/
Look for the "Session cookie setup by the Load-Balancer" section.

Hope it helps.

**Comment by redgeoff** [comment]
@peanutpi this is great. So I'd need something like:

```
backend couchdbs
        log global
        option httpchk GET /_up
        http-check disable-on-404
        cookie AuthSession insert indirect nocache
        server couchdb1 couchdb1:5984 check inter 5s cookie
        server couchdb2 couchdb2:5984 check inter 5s cookie
        server couchdb3 couchdb3:5984 check inter 5s cookie
```

Is there something needed at the end of `server couchdb1 couchdb1:5984 check inter 5s cookie` lines?

Sorry, but the documentation is a little unclear to me and I am an haproxy noob.

**Comment by peanutpi** [comment]
@redgeoff : you've to configure the haproxy like following for all of your node

```
backend couchdbs
        log global
        option httpchk GET /_up
        http-check disable-on-404
        cookie AuthSession insert indirect nocache
        server couchdb1 couchdb1:5984 check inter 5s cookie couchdb1
        server couchdb2 couchdb2:5984 check inter 5s cookie couchdb2
        server couchdb3 couchdb3:5984 check inter 5s cookie couchdb3
```
- What this will do is create a new cookie with value as a service name & next time when that same user will create a new request haproxy will route that user to the same service instance based on the cookie value.

- Apart from that you've to configure a key in the couchdb home directory so that when you restart one of the node in the cluster they'll automatically connect to the cluster based on the key. So for couchdb the key will work as to identify the cluster. by default it'll generate a random string for the key.

**Comment by redgeoff** [comment]
@peanutpi you rock! I managed to make [these changes](https://github.com/redgeoff/couchdb-docker/commit/4fed77b63e0f3e6444ee52ed7966f965dce9ed37) and now the requests are routed to the correct server via haproxy!

Here's what I ended up. It's pretty much identical to the config at http://www.haproxy.com/blog/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know. The cookie name needs to be something other than `AuthSession` as `AuthSession` is reserved for the cookie used by CouchDB. Instead we need a second cookie, e.g. `SERVERID`, that stores the server id/name so that haproxy knows how to route subsequent requests.

```
backend couchdbs
        option httpchk GET /_up
        http-check disable-on-404
        cookie SERVERID insert indirect nocache
        server couchdb1 couchdb1:5984 check inter 5s cookie couchdb1
        server couchdb2 couchdb2:5984 check inter 5s cookie couchdb2
        server couchdb3 couchdb3:5984 check inter 5s cookie couchdb3
```

**Comment by peanutpi** [comment]
@redgeoff : did you configure the key in docker container ?

**Comment by redgeoff** [comment]
@peanutpi, yes, [I modified docker-entrypoint.sh](https://github.com/redgeoff/couchdb-docker/commit/4fed77b63e0f3e6444ee52ed7966f965dce9ed37#diff-bd80af5188e025631ac33c4a452236b6R44) to allow for a `secret` to be configured. I then [set the secret in the docker-compose.yml](https://github.com/redgeoff/couchdb-docker/commit/4fed77b63e0f3e6444ee52ed7966f965dce9ed37#diff-a5db8add34c45010072572f34c67e041R12).

**Comment by redgeoff** [comment]
Thanks to @janl's help, I've managed to get around the sticky sessions by using the exact same line (including the pbkdf2 hash) in the [admins] section of local.ini on all my nodes. I was then able to disable sticky load balancing in haproxy and the admin session persists across all nodes!

Details of my change can be found at http://stackoverflow.com/q/43958527/2831606. The specific commit is redgeoff/couchdb-docker@f4952a7
