### ISSUE TITLE
Eventsource seems to be broken for _changes endpoint

### ISSUE THREAD

**Issue by abhishiv** [klaemo/docker-couchdb#95]
It seems to close to connection after the first heartbeat is sent.

This only happens when I use this docker image, and not the one compiled manually.

Using 2.0.0 single 

Public Example: https://relax0.grati.co/project-990231552b1542c1b7938ed5f74fce39-branch-master/_changes?heartbeat=5000&feed=eventsource&descending=false&since=now

Any idea what could be the problem?

**Comment by garrensmith** [comment]
Could you send us some of the couchdb and dockers logs so we can get more of an idea of what is happening.

**Comment by abhishiv** [comment]
Hey @garrensmith 

Actually was an issue with couch not docker or this image. See COUCHDB-3164 if interested.

I managed to fix it by manually applying the patch from that bug.

Thanks!

**Comment by garrensmith** [comment]
Awesome Great to hear. I'm closing this ticket then.
