### ISSUE TITLE
Looking for a (co-)maintainer

### ISSUE THREAD

**Issue by klaemo** [klaemo/docker-couchdb#97]
As you might have noticed I haven't been that responsive lately.

I don't use docker couchdb that much anymore and haven't even dug into CouchDB 2.0 at all.
It'd be rad if someone were willing to step up and help maintain this project. Of course, I'll be available to answer any questions.

If you're interested, just let me know here or on twitter.

Thank you!

**Comment by zemirco** [comment]
I can help. Just not using CouchDB 2.0 at the moment. I want to switch to the current version though. Just need to read and learn more about the setup process.

**Comment by kocolosk** [comment]
I'm spread pretty thin but I'm very interested in smoothing out the container-based deployment of 2.0 clusters. I can devote some time there for sure.

**Comment by klaemo** [comment]
🎉 Yay! Thank you! As I know that your both active members of the CouchDB community, I added you as collaborators. 
If you want to make changes to the images, please open PRs so we can review the changes together. If there are any problems regarding docker hub (because this is based on my account there), just ping me. 

The next big step is getting 2.0 ready for submission as an official image. And providing appropriate documentation (clustered and non-clustered setups).

I'm so happy you two and @garrensmith stepped up so quickly :)

**Comment by James1912** [comment]
I would love to help out here where I can.  I have used these containers a bunch so it's about time I give back here.

**Comment by dcheese** [comment]
I'm willing to help out here where/when I can.

**Comment by garrensmith** [comment]
Clemens I think it would be best now to create a few issues on what you need done so everyone can help where they can. 
All misspelling thanks to my iPhone.




On Thu, Nov 17, 2016 at 8:16 PM +0200, "Dan Cheeseman" <notifications@github.com> wrote:












I'm willing to help out here where/when I can.

**Comment by klaemo** [comment]
Hey, thanks for the interest, y'all :)

So, the main topics currently are:

- Creating an official 2.0 image: https://github.com/klaemo/docker-couchdb/issues/98 (I added some notes about the process)
- Fulltext search for 2.0: https://github.com/klaemo/docker-couchdb/issues/48 (this would be super nice to have as it's been requested a bunch of times, but I don't have any knowledge about this)
- Documentation about running a cluster: https://github.com/klaemo/docker-couchdb/issues/93 (it'd be nice if we had some documentation, because this has come up quite a bit)
- cleaning up the README in general, might be a good idea

Besides that I appreciate any help answering people's `2.0` questions. Garren has already done an amazing job cleaning up the issues :)

Thank you! I'm going to close this for now as I think enough people are willing to volunteer :) But feel free to post questions in here.
