### ISSUE TITLE
Create official CouchDB 2.0 image

### ISSUE THREAD

**Issue by garrensmith** [klaemo/docker-couchdb#98]
I don't know what the process is, what is required to get an image marked as official?

**Comment by klaemo** [comment]
The process is described in the [docker-library/official-images](https://github.com/docker-library/official-images) github repo.
The image for `1.6.1` is official so its Dockerfile could be used as inspiration, but I think the `2.0.0` is already pretty close. What's left is adding GPG signature checking, I think. Then you can submit a PR to the `official-images` repo (mentioned above).

Also, they require documentation to be added to [docker-library/docs](https://github.com/docker-library/docs). The documentation for 1.6 exists and needs to be amended with 2.0 specific bits. I think a simple cluster setup guide would be very helpful to people.

Here's the PR that added `1.6` as an official image:
https://github.com/docker-library/official-images/pull/1288

Here's the PR that added `1.6` documentation:
https://github.com/docker-library/docs/pull/495

Thanks! If you have any questions, let me know!

**Comment by klaemo** [comment]
I just added GPG signature verification to the `2.0.0` image. I would be okay with submitting that to the official repo.

We still need to take care of the documentation, though.

**Comment by garrensmith** [comment]
Kamino closed and cloned this issue to apache/couchdb-docker
